### PR TITLE
Android SAML template app

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by danielpassos** [comment]
@edewit @corinnekrych @abstractj Could you give it a spin?

**Comment by corinnekrych** [comment]
:eyes:

**Comment by edewit** [comment]
:sunglasses:

**Comment by edewit** [comment]
Could you add a "sign in again" button? To demonstrate that one only need to sign in once?

**Comment by edewit** [comment]
other then that :+1:

**Comment by corinnekrych** [comment]
+1 to merge once you put the "sign in again", I've put it back on iOS version

**Comment by danielpassos** [comment]
@corinnekrych @edewit Done!

**Comment by abstractj** [comment]
@danielpassos landed, thank you

**Pull request merged**
